#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9204CB5BFBF0221 (bkorb@gnu.org)
#
Name     : sharutils
Version  : 4.15.2
Release  : 10
URL      : https://mirrors.kernel.org/gnu/sharutils/sharutils-4.15.2.tar.xz
Source0  : https://mirrors.kernel.org/gnu/sharutils/sharutils-4.15.2.tar.xz
Source99 : https://mirrors.kernel.org/gnu/sharutils/sharutils-4.15.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-3.0
Requires: sharutils-bin
Requires: sharutils-doc
Requires: sharutils-locales
BuildRequires : bison
Patch1: cve-2018-1000097.patch

%description
This is the set of GNU shar utilities.
"sharutils" is licensed under the terms of the GNU GPL version 3 (or, at your
option, any later version).

%package bin
Summary: bin components for the sharutils package.
Group: Binaries

%description bin
bin components for the sharutils package.


%package doc
Summary: doc components for the sharutils package.
Group: Documentation

%description doc
doc components for the sharutils package.


%package locales
Summary: locales components for the sharutils package.
Group: Default

%description locales
locales components for the sharutils package.


%prep
%setup -q -n sharutils-4.15.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526019661
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1526019661
rm -rf %{buildroot}
%make_install
%find_lang sharutils

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/shar
/usr/bin/unshar
/usr/bin/uudecode
/usr/bin/uuencode

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files locales -f sharutils.lang
%defattr(-,root,root,-)

